"""Stub of the Master Resonant Index (MRI) utilities."""

from typing import Any


def validate_resonance(data: Any) -> bool:
    """Placeholder for resonance validation.

    Parameters
    ----------
    data : Any
        Data generated by the pipeline up to Yesod.

    Returns
    -------
    bool
        Always ``True`` for now.
    """
    # Future implementations should measure resonance between ``data``
    # and stored vectors from the MRI.  This stub simply returns ``True``.
    return True
