version: 1
formatters:
  default:
    format: '%(asctime)s — %(levelname)s — %(name)s — %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: desktop_app/logs/caelus.log
    maxBytes: 10485760  # 10 MB
    backupCount: 3
    formatter: default
root:
  level: INFO
  handlers: [file]
