# \u25b6 PROMPT\u00a0P\u201143
name: Audit Skeleton
on: [pull_request]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install termcolor
      - run: python scripts/audit_repo.py --expected-file expected_files.json
