name: Build & Release GUI
on:
  push:
    tags: ['v*']
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt pyinstaller pyside6
      - run: pyinstaller desktop_app/resources/installer.spec
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/CaelusIntegratedAgents.exe
